# Generated by Django 3.0.6 on 2020-05-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='messages',
            field=models.ManyToManyField(blank=True, to='user.Message'),
        ),
        migrations.AddField(
            model_name='user',
            name='request_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='thread',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
