# Generated by Django 3.0.6 on 2020-05-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_access_token_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
